resources:
- name: concourse-helm-resource
  type: git
  source:
    uri: git@github.com:helix-re/concourse-helm-resource.git
    branch: master

- name: docker-image
  type: docker-image
  source:
    repository:  us.gcr.io/helix-global/concourse-helm-resource
    username: _json_key
    password: ((k8s-service-account))
    params:
      build: concourse-helm-resource/.ci/

jobs:
- name: build-docker-image
  plan:
  - get: concourse-helm-resource
    trigger: false
  - put: docker-image
    params:
      build:
