
resource_types:
resources:
- name: concourse-helm-resource
  type: git
  source:
    repo: helix-re/concourse-helm-resource
    branch: master
    uri: git@github.com:helix-re/concourse-helm-resource.git
    private_key: ((concourse-helm-resource-deploy-key))
- name: docker
  type: docker-image
  source:
    repository: us.gcr.io/helix-global/concourse-helm-resource
    username: _json_key
    password: ((helix-global-k8s-service-account))
jobs:
- name: build_docker_image
  plan:
  - get: concourse-helm-resource
  - task: debug
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
          tag: 3.7
      inputs:
        - name: concourse-helm-resource
      run:
        path: /bin/sh
        args: ["-c", "ls", "-l"]
    trigger: false
  - put: docker
    params:
      build: concourse-helm-resource/
    get_params:
      skip_download: true
