resource_types:
resources:
- name: build_number
  type: semver
  source:
    driver: gcs
    initial_version: 0.0.1
    bucket: helix-global-concourse-semvar
    key: concourse/concourse-helm-resource
    json_key: ((helix-global-k8s-service-account))
- name: concourse-helm-resource
  type: git
  source:
    repo: helix-re/concourse-helm-resource
    branch: master
    uri: git@github.com:helix-re/concourse-helm-resource.git
    private_key: ((helix-ci-github-ssh-key))
- name: docker
  type: docker-image
  source:
    repository: us.gcr.io/helix-global/concourse-helm-resource
    username: _json_key
    password: ((helix-global-k8s-service-account))

jobs:
- name: build_docker_image
  plan:
  - get: build_number
  - get: concourse-helm-resource
    trigger: true
  - put: docker
    params:
      build: concourse-helm-resource/
      tag: build_number/number
      tag_as_latest: true
      cache: true
      cache_tag: latest
    get_params:
      skip_download: true
  - put: build_number
    params:
      bump: patch
