
resource_types:
resources:
- name: concourse-helm-resource-master
  type: git
  source:
    repo: helix-re/concourse-helm-resource
    branch: master
    uri: git@github.com:helix-re/concourse-helm-resource.git
    private_key: ((concourse-helm-resource-deploy-key))
- name: docker
  type: docker-image
  source:
    repository: us.gcr.io/helix-global/concourse-helm-resource
    username: _json_key
    password: ((helix-global-k8s-service-account))
jobs:
- name: build_docker_image
  plan:
  - get: concourse-helm-resource-master
    trigger: false
  - put: docker
    params:
      build: concourse-helm-resource/.ci
    get_params:
      skip_download: true
